name: build-and-deploy
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: true

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm build-storybook

      - name: Deploy
        run: |
          pnpm swa deploy ./storybook-static --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} --env ${{ inputs.environment_name }}
