name: Hero UI

on:
  push:
    branches:
      - heroui

jobs:
  build-and-deploy:
    name: build-and-deploy
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      environment_name: heroui
    secrets: inherit
