name: Main

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: build-and-deploy
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      environment_name: Production
    secrets: inherit
