name: Production

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    name: build-and-deploy
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      environment_name: production
    secrets: inherit
