name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: build-and-deploy
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      environment_name: development
    secrets: inherit
